
# global configuration
#version: 1.1.5.{build}
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: ./build.ps1



for:
# configuration for master branch
-
  branches:
    only:
      - master
  environment:
      branch: master
  
        
# configuration for develop branch
-
  branches:
    only:
      - develop
  environment:
      branch: develop
        
# configuration for all other branches
-
  environment:
      branch: none
